// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GARCIA_SIA102Midterms.Data
{
    public partial class byroyaltyResult
    {
        [StringLength(11)]
        public string au_id { get; set; }
    }
}
