// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using GARCIA_SIA102Midterms.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace GARCIA_SIA102Midterms.Data
{
    public partial interface IpubsContextProcedures
    {
        Task<List<byroyaltyResult>> byroyaltyAsync(int? percentage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<reptq1Result>> reptq1Async(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<reptq2Result>> reptq2Async(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<reptq3Result>> reptq3Async(decimal? lolimit, decimal? hilimit, string type, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
