// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GARCIA_SIA102Midterms.Data
{
    public partial class reptq2Result
    {
        [StringLength(12)]
        public string type { get; set; }
        [StringLength(4)]
        public string pub_id { get; set; }
        public int? avg_ytd_sales { get; set; }
    }
}
