// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GARCIA_SIA102Midterms.Data
{
    public partial class reptq1Result
    {
        [StringLength(4)]
        public string pub_id { get; set; }
        [Column("avg_price", TypeName = "money")]
        public decimal? avg_price { get; set; }
    }
}
